name: "Integration Tests"
on:
  workflow_call:

jobs:
  run-action-on-mock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Update action.yml docker version
        uses: ValoriaTechnologia/FieldChartUpdater@v0.1.2
        with:
          file: ./action.yml
          edits: '[{"path": "runs.image", "value": "Dockerfile"}]'

      - name: Run action on ArgoHelmDeploy-Mock
        uses: ./
        with:
          repo_url: 'https://github.com/ValoriaTechnologia/ArgoHelmDeploy-Mock.git'
          token: ${{ secrets.TOKEN_MOCK_REPO }}
          package_file_path: 'packages.yaml'
          package_name: 'argo-app'
          version: ${{ github.event.inputs.version || '2.0.0' }}
          chart_name: 'my-chart'
          branch: 'main'

      - name: Run action on ArgoHelmDeploy-Mock
        uses: ./
        with:
          repo_url: 'https://github.com/ValoriaTechnologia/ArgoHelmDeploy-Mock.git'
          token: ${{ secrets.TOKEN_MOCK_REPO }}
          package_file_path: 'packages.yaml'
          package_name: 'argo-app2'
          version: ${{ github.event.inputs.version || '2.0.0' }}
          chart_name: 'my-chart'
          branch: 'main'
          environment: 'dev'
